codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  range: "50...100"

flags:
  backend:
    paths:
      - Proj2/backend/
  frontend:
    paths:
      - Proj2/frontend/src/

ignore:
  - "Proj2/backend/venv"
  - "Proj2/backend/tests"
  - "Proj2/frontend/node_modules"
  - "**/*.test.js"
